# cloudbuild.yaml

options:
  logging: 'CLOUD_LOGGING_ONLY'

steps:
  # Step 1: Build the Docker image
  - id: "Build image"
    name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/$PROJECT_ID/$_SERVICE_NAME',
        '--build-arg',
        'ENVIRONMENT=production',
        '.',
      ]

  # Step 2: Push the Docker image to Container Registry
  - id: "Push image"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME']

  # Step 3: Deploy to Cloud Run
  - id: "Deploy to Cloud Run"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy $_SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$_SERVICE_NAME \
          --platform managed \
          --region $_REGION \
          --allow-unauthenticated \
          --add-cloudsql-instances $PROJECT_ID:$_REGION:$_INSTANCE_NAME \
          --set-env-vars ENVIRONMENT=production,PROJECT_ID=$PROJECT_ID

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME'

substitutions:
  _SERVICE_NAME: 'samaanai_service'       # Replace with your Cloud Run service name
  _REGION: 'us-west1'                     # Replace with your Cloud Run service region
  _INSTANCE_NAME: 'mypostgres'            # Replace with your Cloud SQL instance name
