# Generated by Django 4.2.7 on 2025-02-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['user', 'provider'], name='core_userto_user_id_5f9264_idx'),
        ),
    ]
