# Generated by Django 4.2.7 on 2025-02-24 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usertoken_core_userto_user_id_5f9264_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
