# Generated by Django 4.2.7 on 2025-02-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='list_code',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='list_name',
            field=models.CharField(max_length=200),
        ),
    ]
