# Generated by Django 4.2.7 on 2025-02-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0002_alter_tasklist_list_code_alter_tasklist_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_name',
            field=models.CharField(max_length=2000),
        ),
    ]
