# Generated by Django 4.2.7 on 2025-02-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0003_task_task_manage_user_id_06c0ac_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='list_source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
