# Generated by Django 4.2.7 on 2025-02-25 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_management', '0004_tasklist_list_source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklist',
            options={'ordering': ['list_name']},
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='special_list',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='list_type',
            field=models.CharField(choices=[('special', 'Special'), ('google_primary', 'Google Primary'), ('microsoft_primary', 'Microsoft Primary'), ('normal', 'Normal')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='list_source',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
