# Generated by Django 4.2.7 on 2024-12-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_tasklist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='color',
        ),
    ]
