# Generated by Django 4.2.7 on 2024-12-27 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_remove_tasklist_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
