# Generated by Django 4.2.7 on 2023-12-02 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0004_task_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=2000)),
                ('list_code', models.CharField(max_length=100, null=True)),
                ('special_list', models.BooleanField(default=False)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=2000)),
                ('due_date', models.DateTimeField()),
                ('reminder_Time', models.DateTimeField(default=django.utils.timezone.now)),
                ('recurrence', models.CharField(blank=True, max_length=100)),
                ('task_completed', models.BooleanField(default='False')),
                ('important', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(max_length=100, null=True)),
                ('task_image', models.FileField(blank=True, null=True, upload_to='')),
                ('creation_date', models.DateField(verbose_name='2023-12-02')),
                ('last_update_date', models.DateField(verbose_name='2023-12-02')),
                ('list_name', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='todos.task_lists')),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
