# Generated by Django 4.2.7 on 2023-12-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_task_lists_tasks_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='creation_date',
            field=models.DateField(verbose_name='2023-12-03'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='last_update_date',
            field=models.DateField(verbose_name='2023-12-03'),
        ),
    ]
