# Generated by Django 4.2.7 on 2023-12-05 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0007_task_rename_task_lists_tasklist_delete_tasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_list',
            new_name='list_name',
        ),
        migrations.AlterField(
            model_name='task',
            name='reminder_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
