# Generated by Django 4.2.7 on 2023-12-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='imageblank.png', max_length=255),
        ),
    ]
