# Generated by Django 4.2.7 on 2023-12-18 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todos', '0010_image_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_image',
        ),
        migrations.AlterField(
            model_name='task',
            name='recurrence',
            field=models.CharField(blank=True, choices=[('NO_RECURRENCE', 'No Recurrence'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=100),
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('task_description', models.CharField(max_length=2000)),
                ('due_date', models.DateTimeField()),
                ('reminder_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('recurrence', models.CharField(blank=True, max_length=100)),
                ('task_completed', models.BooleanField(default=False)),
                ('important', models.BooleanField(default=False)),
                ('assigned_to', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('list_name', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='todos.tasklist')),
                ('user', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
            },
        ),
    ]
