# Generated by Django 4.2.7 on 2023-12-28 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0012_tasklist_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='test_field',
        ),
    ]
