# Generated by Django 4.2.7 on 2023-12-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0013_remove_tasklist_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
