# Generated by Django 4.2.7 on 2024-01-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0016_alter_task_reminder_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='task_description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
