# Generated by Django 4.2.7 on 2024-02-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_stock_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
