# Generated by Django 4.2.7 on 2024-02-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_purchased',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
